"""
build_animals_js.py  —  Wild Range data pipeline, Step 2
─────────────────────────────────────────────────────────
Reads:
  review/animals_meta.csv
  review/animals_ranges.geojson
  review/animals_images.json

Writes:
  ../data/animals.js
"""

import csv, json, os, sys

REVIEW_DIR     = os.path.join(os.path.dirname(__file__), "review")
META_CSV       = os.path.join(REVIEW_DIR, "animals_meta.csv")
RANGES_GEOJSON = os.path.join(REVIEW_DIR, "animals_ranges.geojson")
IMAGES_JSON    = os.path.join(REVIEW_DIR, "animals_images.json")
OUTPUT_JS      = os.path.join(os.path.dirname(__file__), "..", "data", "animals.js")

VALID_STATUSES = {"CR","EN","VU","NT","LC","DD","NE"}
MAX_VERTICES   = 120


def simplify_ring(ring, max_pts):
    if len(ring) <= max_pts: return ring
    step = (len(ring)-1)/(max_pts-1)
    indices = set([0, len(ring)-1])
    for i in range(1, max_pts-1): indices.add(round(i*step))
    return [ring[i] for i in sorted(indices)]


def load_meta():
    rows = {}; warnings = []; errors = []
    with open(META_CSV, encoding="utf-8") as f:
        for i, row in enumerate(csv.DictReader(f), 2):
            aid = row.get("id","").strip()
            if not aid or row.get("include","yes").strip().lower() == "no":
                if aid: print(f"  ⏭  Skipping {row.get('name','?')}")
                continue
            status = row.get("status","LC").strip().upper()
            if status not in VALID_STATUSES:
                errors.append(f"Row {i} ({aid}): invalid status '{status}'")
            if not row.get("fact","").strip():
                warnings.append(f"  ⚠  {row.get('name','?')}: missing fact")
            if not row.get("region","").strip():
                warnings.append(f"  ⚠  {row.get('name','?')}: missing region")
            rows[aid] = {
                "id":              aid,
                "scientific_name": row.get("scientific_name","").strip(),
                "name":            row.get("name","").strip(),
                "emoji":           row.get("emoji","🐾").strip(),
                "hint":            row.get("hint","").strip() or f"A {row.get('name','')}",
                "status":          status if status in VALID_STATUSES else "LC",
                "region":          row.get("region","").strip() or "Global",
                "fact":            row.get("fact","").strip() or f"The {row.get('name','')} is a fascinating species.",
            }
    return rows, warnings, errors


def load_ranges():
    with open(RANGES_GEOJSON, encoding="utf-8") as f:
        gj = json.load(f)
    ranges = {}
    for feat in gj.get("features",[]):
        aid  = feat.get("properties",{}).get("id","").strip()
        geom = feat.get("geometry",{})
        if not aid or not geom: continue
        geom_type = geom.get("type"); coords = geom.get("coordinates",[])
        rings = []
        if geom_type == "Polygon":
            rings.append(coords[0])
        elif geom_type == "MultiPolygon":
            for poly in coords:
                if poly: rings.append(poly[0])
        converted = []
        for ring in rings:
            s = simplify_ring(ring, MAX_VERTICES)
            gr = [{"lat":round(c[1],4),"lng":round(c[0],4)} for c in s]
            if gr and gr[0] != gr[-1]: gr.append(gr[0])
            if len(gr) >= 4: converted.append(gr)
        if converted: ranges[aid] = converted
    return ranges


def load_images():
    if not os.path.exists(IMAGES_JSON): return {}
    with open(IMAGES_JSON, encoding="utf-8") as f:
        return json.load(f)


def esc(s):
    return s.replace("\\","\\\\").replace("'","\\'")


def run():
    print(f"\n🌿 Wild Range — build pipeline\n")
    for p,l in [(META_CSV,"animals_meta.csv"),(RANGES_GEOJSON,"animals_ranges.geojson")]:
        if not os.path.exists(p):
            print(f"❌ Missing: {p} — run fetch_animals.py first"); sys.exit(1)

    print(f"📄 Loading metadata...")
    meta, warnings, errors = load_meta()
    for w in warnings: print(w)
    for e in errors:   print(f"  ❌ {e}")
    if errors: print(f"\n❌ Fix errors above then re-run.\n"); sys.exit(1)
    print(f"   {len(meta)} species\n")

    print(f"🗺  Loading ranges...")
    ranges = load_ranges()
    print(f"   {len(ranges)} species with polygons\n")

    print(f"📷 Loading images...")
    images = load_images()
    print(f"   {len(images)} species with images\n")

    lines = []
    lines.append("// AUTO-GENERATED by pipeline/build_animals_js.py")
    lines.append("// Edit review/animals_meta.csv, animals_ranges.geojson, animals_images.json then re-run")
    lines.append("")
    lines.append("const ANIMALS = [")

    included = 0
    for aid, m in meta.items():
        polys = ranges.get(aid)
        if not polys:
            print(f"  ⚠  {m['name']}: no range — excluded"); continue

        img = images.get(aid, {})
        img_url    = img.get("url","")
        img_credit = img.get("rightsHolder","")
        img_license= img.get("license","")

        # Format polygons
        poly_strs = []
        for poly in polys:
            pts = ",".join(f"{{lat:{p['lat']},lng:{p['lng']}}}" for p in poly)
            poly_strs.append(f"    [{pts}]")
        range_str = "[\n" + ",\n".join(poly_strs) + "\n  ]"

        lines.append("  {")
        lines.append(f"    id: '{esc(aid)}',")
        lines.append(f"    name: '{esc(m['name'])}',")
        lines.append(f"    scientificName: '{esc(m['scientific_name'])}',")
        lines.append(f"    emoji: '{m['emoji']}',")
        lines.append(f"    hint: '{esc(m['hint'])}',")
        lines.append(f"    status: '{m['status']}',")
        lines.append(f"    fact: '{esc(m['fact'])}',")
        lines.append(f"    region: '{esc(m['region'])}',")
        lines.append(f"    image: '{esc(img_url)}',")
        lines.append(f"    imageCredit: '{esc(img_credit)}',")
        lines.append(f"    imageLicense: '{esc(img_license)}',")
        lines.append(f"    rangePolygons: {range_str},")
        lines.append("  },")
        included += 1

    lines.append("];")
    lines.append("")
    lines.append("const STATUS_META = {")
    lines.append("  CR: { label: 'Critically Endangered', color: '#791F1F', bg: '#FCEBEB', order: 0 },")
    lines.append("  EN: { label: 'Endangered',            color: '#993C1D', bg: '#FAECE7', order: 1 },")
    lines.append("  VU: { label: 'Vulnerable',            color: '#854F0B', bg: '#FAEEDA', order: 2 },")
    lines.append("  NT: { label: 'Near Threatened',       color: '#3B6D11', bg: '#EAF3DE', order: 3 },")
    lines.append("  LC: { label: 'Least Concern',         color: '#0F6E56', bg: '#E1F5EE', order: 4 },")
    lines.append("  DD: { label: 'Data Deficient',        color: '#444441', bg: '#F1EFE8', order: 5 },")
    lines.append("};")
    lines.append("")
    lines.append("const STATUS_ORDER = ['CR','EN','VU','NT','LC','DD'];")

    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✅ Written {included} animals → {OUTPUT_JS}\n")

if __name__ == "__main__":
    run()
